// ═══════════════════════════════════════════════════════════════════
// password.js  —  Password strength, validation, confirm matching,
//                 passphrase generator, and keyfile handling
// ═══════════════════════════════════════════════════════════════════
"use strict";

// ── Strength indicator ───────────────────────────────────────────────

function checkPasswordStrength() {
    const pw = document.getElementById("password").value;
    const el = document.getElementById("passwordStrength");
    if (!pw) { el.textContent = ""; el.style.color = ""; return; }
    let score = 0;
    if (pw.length >= MIN_PASSWORD_LEN) score++;
    if (pw.length >= 12) score++;
    if (/[A-Z]/.test(pw)) score++;
    if (/[0-9]/.test(pw)) score++;
    if (/[^A-Za-z0-9]/.test(pw)) score++;
    const levels = [
        { label: "Very weak",   color: "#cc2020" },
        { label: "Weak",        color: "#d05000" },
        { label: "Fair",        color: "#c08000" },
        { label: "Strong",      color: "#80c000" },
        { label: "Very strong", color: "#00c060" },
        { label: "Excellent",   color: "#00e8a0" },
    ];
    const lvl = levels[Math.min(score, levels.length - 1)];
    el.textContent = lvl.label;
    el.style.color = lvl.color;
}

function validatePassword(pw) {
    if (!pw) throw new TSFError("validation", "Password is required");
    if (pw.length < MIN_PASSWORD_LEN)
        throw new TSFError("validation", `Password too short — minimum ${MIN_PASSWORD_LEN} characters`);
}

// ── Confirm field ────────────────────────────────────────────────────

function checkConfirmMatch() {
    const pw  = document.getElementById("password").value;
    const cpw = document.getElementById("passwordConfirm").value;
    const msg = document.getElementById("confirmMatchMsg");
    if (!cpw) { msg.textContent = ""; msg.className = ""; return; }
    if (pw === cpw) {
        msg.textContent = "✓ Match";
        msg.className   = "match";
    } else {
        msg.textContent = "✗ No match";
        msg.className   = "nomatch";
    }
}

// ── Show/hide toggles ────────────────────────────────────────────────

function toggleShowPassword() {
    const el = document.getElementById("password");
    el.type = el.type === "password" ? "text" : "password";
    // Each field's visibility is controlled independently by its own button.
    // Syncing passwordConfirm here was asymmetric: clicking "show confirm"
    // then "show password" could leave both visible while only one button
    // appeared pressed, and a second click would hide both unexpectedly.
}

function toggleShowConfirm() {
    const el = document.getElementById("passwordConfirm");
    el.type = el.type === "password" ? "text" : "password";
}

// ── Passphrase generator ─────────────────────────────────────────────
//
// Wordlist: 7776 words drawn from the American English dictionary,
// filtered to 4-8 characters, all lowercase, no abbreviations.
// 7776 = 6^5 (one Diceware die roll per word).
// Entropy: ~12.92 bits/word → 8 words ≈ 103 bits.
//
// Bias note: rejection sampling is used so every word is equally likely.
// The rejection threshold discards values ≥ 4 294 964 736 (≈ 0.0001% of draws).

const PP_WORDS = [
    "aardvark", "abaci", "aback", "abacus", "abacuses", "abaft", "abalone", "abalones",
    "abandon", "abandons", "abase", "abased", "abases", "abash", "abate", "abated",
    "abating", "abbeys", "abdomens", "abeam", "abet", "abettor", "abhor", "abhorred",
    "abhors", "abject", "ablest", "abode", "abolish", "abortive", "aborts", "above",
    "abridge", "abroad", "abruptly", "absinth", "absolved", "absorb", "abuses", "abusive",
    "abut", "abutment", "abuzz", "academy", "accent", "accesses", "acclaim", "accord",
    "accrued", "accruing", "acerbic", "aces", "acetic", "ached", "achieved", "achy",
    "acidic", "acidify", "acids", "acne", "acorn", "acquires", "acquit", "acreage",
    "acted", "actions", "activate", "active", "acuity", "acute", "acutes", "acutest",
    "adapters", "adaptor", "added", "addend", "adding", "adds", "adduce", "adduced",
    "adenoids", "adept", "adheres", "adieux", "adjourns", "adjured", "adjust", "adman",
    "admirals", "admirer", "admit", "admits", "adorably", "adore", "adores", "adroit",
    "adulate", "adverb", "adverser", "adverts", "adware", "adze", "adzes", "aeons",
    "aerates", "aeration", "aeries", "afar", "affable", "affirm", "affixes", "afflicts",
    "afghans", "afield", "afire", "afraid", "after", "agate", "ageing", "agent",
    "agents", "ages", "agility", "agism", "agitated", "agleam", "agree", "agronomy",
    "ague", "aide", "aides", "aiding", "aileron", "aimed", "aims", "airfoils",
    "airhead", "airily", "airline", "airmen", "airships", "airy", "akimbo", "alarm",
    "alarmed", "alas", "albums", "alcohol", "alcohols", "alert", "alerts", "alga",
    "alias", "aliased", "aliening", "alight", "align", "aligned", "alive", "alkali",
    "alleges", "allegros", "alleys", "allot", "allots", "alloy", "alloyed", "alloying",
    "allure", "allying", "almighty", "alms", "aloha", "alohas", "aloof", "alpine",
    "alright", "also", "altar", "altho", "alum", "alumni", "amalgams", "amass",
    "amasses", "amazes", "ambient", "amble", "ambles", "ambushes", "amebic", "amend",
    "amidst", "amino", "amir", "amity", "ammeter", "amoebas", "amok", "amoral",
    "amounted", "ample", "ampler", "amplest", "ampul", "amulet", "amulets", "analog",
    "analogy", "analysis", "anatomy", "ancestor", "android", "anecdote", "anew", "angel",
    "angels", "angled", "angling", "angora", "angry", "animals", "animists", "anion",
    "ankhs", "ankles", "anklets", "anneal", "annoy", "annuity", "annuls", "anointed",
    "anons", "anoraks", "answer", "ante", "antennas", "anthems", "anther", "antic",
    "antimony", "antique", "ants", "anuses", "anvil", "anybody", "anyway", "apart",
    "apathy", "aperitif", "apes", "aphelia", "apiary", "apogee", "apostate", "appal",
    "apparel", "appeal", "appeases", "applaud", "apples", "appraise", "approve", "apricots",
    "apron", "apse", "apter", "aquas", "aquatic", "arable", "arbiters", "arcades",
    "arcane", "arch", "arches", "arching", "ardent", "ardently", "ardor", "arena",
    "ares", "argosy", "argue", "argues", "arguing", "arises", "arks", "armband",
    "armed", "armholes", "armies", "armors", "armpits", "arose", "around", "arouses",
    "arranged", "arrays", "arrival", "arrow", "arrows", "arsenals", "arsenic", "artier",
    "artifice", "artless", "arts", "ascent", "ascetic", "ascetics", "ascot", "ashes",
    "ashier", "ashiest", "ashy", "asides", "askew", "asleep", "asocial", "aspic",
    "aspics", "aspirins", "assails", "assent", "assessed", "asset", "assets", "asshole",
    "assize", "assumed", "assuming", "astern", "astir", "astral", "astride", "asylum",
    "ateliers", "atheism", "atoms", "atoned", "atop", "atria", "atriums", "attach",
    "attained", "attend", "attests", "attune", "attunes", "attuning", "audio", "auditors",
    "audits", "aught", "augment", "augurs", "auks", "aunts", "auras", "auricle",
    "auricles", "autism", "auto", "autumnal", "availed", "avast", "avatar", "avenues",
    "averse", "avian", "aviaries", "avid", "avidity", "avoids", "avows", "awaits",
    "awakened", "awakens", "awakes", "award", "away", "awful", "awkward", "awls",
    "awning", "axed", "axial", "axiom", "axis", "ayes", "azalea", "azure",
    "babble", "babbles", "babes", "babies", "baby", "babysat", "bachelor", "backer",
    "backhoes", "backing", "backspin", "badge", "badger", "badmouth", "badness", "bagel",
    "bagged", "bagpipe", "bags", "bait", "baits", "baker", "bakers", "balance",
    "balded", "baldness", "balds", "bale", "baling", "balking", "balks", "balled",
    "balloon", "ballsy", "balm", "balmiest", "balms", "banal", "banana", "bananas",
    "bandies", "banditry", "bandy", "bane", "banged", "banjo", "banjoes", "banjos",
    "bank", "bankroll", "banner", "banquet", "banyan", "baptism", "barbacoa", "barber",
    "barbing", "barbs", "bard", "bareness", "barer", "barf", "barfs", "barged",
    "barium", "barking", "barley", "barns", "baronial", "barrack", "barred", "barrio",
    "barrios", "barrooms", "bars", "basalt", "based", "basemen", "bashes", "basic",
    "basin", "basins", "bask", "basses", "bassi", "bassists", "bassoon", "bast",
    "batch", "batches", "bates", "bathed", "bathos", "batik", "batons", "bats",
    "batsmen", "battened", "batting", "battle", "bauds", "bawdily", "bayed", "baying",
    "bays", "beach", "beached", "beacon", "beadiest", "beaker", "beakers", "beaks",
    "beam", "bear", "beard", "beards", "bearers", "beaten", "beating", "beats",
    "beauties", "beaux", "bebops", "beck", "beckon", "beckons", "bedded", "bedevils",
    "bedlams", "bedpan", "bedside", "beech", "beefiest", "beehive", "been", "beeper",
    "beeps", "beer", "beetled", "befall", "befit", "before", "befuddle", "began",
    "beggar", "begin", "begone", "begonia", "begs", "behalves", "beheld", "behests",
    "behold", "beige", "belabors", "belay", "belayed", "belfry", "bellboy", "belle",
    "belled", "bellhops", "belong", "belongs", "below", "bemoans", "bemuse", "benching",
    "bend", "bends", "beneath", "berate", "berated", "bereaves", "beret", "berg",
    "berry", "berthed", "berths", "beset", "beside", "besought", "bespoke", "bestir",
    "bests", "beta", "betaken", "betaking", "betcha", "betoken", "betray", "between",
    "bevel", "beveling", "bevels", "beware", "bewares", "bias", "biases", "biblical",
    "bidden", "bidders", "biddy", "bide", "bidet", "biding", "biff", "bigamist",
    "bigger", "biggest", "bight", "bigwig", "bigwigs", "biked", "bikini", "bilge",
    "bilk", "billed", "billies", "billy", "binaries", "binary", "binders", "binds",
    "binges", "bins", "biology", "biopsy", "biped", "birching", "birdied", "birth",
    "birther", "births", "bisected", "bisons", "bitched", "bitchy", "bite", "bites",
    "bitter", "bitterns", "bitumen", "black", "blacken", "blackout", "blah", "blamed",
    "blammo", "bland", "blandly", "blares", "blarney", "blarneys", "blast", "blazer",
    "blazing", "bleach", "bleak", "bleakest", "bleed", "bleeped", "bleeps", "blenders",
    "blent", "blesses", "bletch", "blew", "blimp", "blinds", "blink", "blinker",
    "blintzes", "bliss", "blitzes", "blivet", "blob", "blobs", "blockade", "blogger",
    "blogs", "blonde", "blood", "blooding", "bloody", "bloomer", "blot", "bloused",
    "blousing", "blower", "blown", "blowout", "blowzy", "bluefish", "bluer", "bluffer",
    "bluing", "blunt", "blur", "blurred", "blurrier", "blurry", "blurs", "board",
    "boarded", "boas", "boasters", "boasts", "boating", "boats", "bobbed", "bobbled",
    "bode", "bodega", "bodegas", "bodes", "bodily", "bogeying", "bogeys", "boggled",
    "boggy", "bogies", "bogs", "bogus", "boil", "boilings", "boinks", "bolas",
    "boldest", "bole", "bolero", "bolts", "bomb", "bombard", "bonbon", "bondage",
    "bonds", "bondsmen", "bones", "bong", "bonged", "bongoes", "bongs", "boning",
    "bonsai", "bonus", "bonuses", "boob", "booed", "boogie", "boogies", "bookie",
    "bookings", "booming", "boon", "boons", "boot", "bootee", "booth", "booties",
    "booty", "boozed", "booziest", "bopped", "bopping", "borax", "bore", "bores",
    "borrow", "bosom", "boss", "bossed", "bossier", "bosun", "botany", "botching",
    "botnets", "bottom", "boulder", "bounce", "bouncers", "bound", "bounder", "bounty",
    "bowel", "bowing", "bowl", "bowlders", "bowlers", "bowls", "bowman", "boxer",
    "boxers", "boys", "brace", "braces", "bracing", "brag", "braggers", "brags",
    "braided", "brain", "brains", "braked", "bramble", "branched", "brandy", "brash",
    "brat", "brattier", "bravado", "brave", "braved", "bravos", "brawled", "brawn",
    "brazen", "breaches", "bread", "breaded", "breaks", "breather", "breaths", "bred",
    "breech", "breviary", "brevity", "brewed", "brews", "bribed", "brick", "bricked",
    "bridal", "bridles", "briefs", "brier", "brighten", "brim", "brimful", "brims",
    "brings", "brink", "brisker", "briskets", "broach", "broad", "broaden", "broadest",
    "brogues", "broils", "broke", "bronchi", "bronchos", "bronco", "brooded", "broods",
    "broom", "brouhaha", "browned", "browns", "brows", "browses", "bruise", "bruisers",
    "brush", "brushes", "brutal", "brutally", "brute", "bubbled", "bucked", "buckler",
    "buckskin", "budded", "buddies", "budge", "budget", "buds", "buffers", "buffet",
    "bugbear", "bugbears", "bugle", "bugled", "bugling", "builds", "bulb", "bulbs",
    "bulgier", "bulgy", "bull", "bulldog", "bulldogs", "bulled", "bullion", "bulls",
    "bullying", "bumbled", "bummed", "bumming", "bumper", "bumpy", "bunches", "bung",
    "bungalow", "bungler", "bunion", "bunks", "bunkum", "bunt", "bunting", "bunts",
    "burble", "burdens", "burg", "burgher", "burghers", "burgle", "buries", "burka",
    "burlier", "burned", "burnt", "burping", "burr", "burro", "burros", "bursitis",
    "bursted", "bursts", "busby", "bush", "bushel", "bushing", "bushy", "busies",
    "bussed", "bust", "buster", "busters", "busywork", "butches", "butt", "butte",
    "butted", "buttock", "button", "buxom", "buyout", "buzzkill", "byelaw", "byelaws",
    "byes", "byline", "byplay", "bytes", "cabana", "cabaret", "cabby", "cabins",
    "caboose", "cabs", "cacao", "cacaos", "cackle", "cackling", "cacti", "cadaver",
    "cadets", "cadge", "cadgers", "cadres", "caffeine", "caftans", "cages", "cagily",
    "cagy", "cairns", "caked", "calcify", "calcines", "caldron", "calfs", "califs",
    "calk", "callable", "called", "callers", "calls", "callus", "caloric", "calved",
    "calypsos", "calyx", "calyxes", "cambia", "came", "cameo", "camera", "campers",
    "campsite", "cams", "canal", "canals", "cancan", "cancans", "candid", "candled",
    "canes", "caning", "cankered", "cannily", "cannon", "canoes", "canon", "canopies",
    "cant", "canter", "canters", "cantos", "cants", "capable", "capers", "capes",
    "capitals", "caplets", "captain", "captains", "captor", "caracul", "caraways", "carbine",
    "carbon", "carbs", "card", "carding", "cardio", "cares", "caressed", "carets",
    "cargo", "caribou", "caring", "caroler", "carolers", "caroms", "carouser", "carp",
    "carpet", "carpets", "carpi", "carrier", "carrot", "carting", "carton", "cartoons",
    "carts", "cascade", "case", "casein", "cases", "cashew", "cashiers", "casket",
    "caskets", "cast", "caste", "casting", "castle", "castling", "casuals", "catalyst",
    "catboat", "catchier", "catchy", "cater", "catered", "cation", "catnaps", "catsup",
    "cattails", "catwalk", "caucus", "caulks", "cause", "caustics", "cave", "caveat",
    "caveats", "caves", "caviled", "cavils", "cavort", "cease", "cedars", "cedes",
    "ceilings", "celesta", "cell", "cellar", "cells", "cenotaph", "censer", "censors",
    "centrals", "century", "cereal", "certify", "cervices", "cesium", "chads", "chaffs",
    "chain", "chaining", "chaired", "chalet", "chamber", "chambray", "chammy", "champ",
    "chances", "chancy", "changing", "chanter", "chap", "chapel", "chaplets", "chaps",
    "chapter", "charier", "charisma", "charm", "charred", "charts", "chary", "chases",
    "chassis", "chastise", "chat", "chats", "cheapen", "cheapens", "cheats", "check",
    "checked", "cheekily", "cheeky", "cheep", "cheered", "cheery", "cheetahs", "chemist",
    "cherub", "chess", "chessman", "chew", "chewer", "chewers", "chewy", "chicken",
    "chicks", "chide", "chiefs", "chiffon", "chignons", "chile", "chiller", "chilli",
    "chime", "chimed", "chimeras", "chin", "chink", "chinos", "chins", "chintzy",
    "chisel", "chiseled", "chisels", "chits", "chocks", "choicest", "choir", "choker",
    "cholera", "chomps", "chop", "chopped", "chopping", "choppy", "chops", "chore",
    "chorus", "chowing", "chrome", "chromium", "chuck", "chuckle", "chug", "chummy",
    "chums", "church", "churches", "churn", "chutes", "chyrons", "cider", "ciders",
    "cinch", "cinches", "cinchona", "cinema", "circlet", "circular", "circus", "cites",
    "citing", "citrons", "city", "civets", "civic", "civilize", "clacks", "claim",
    "clamber", "clamor", "clamping", "clan", "clang", "clangor", "claps", "claret",
    "clarion", "clashing", "clasp", "classed", "clause", "claw", "clayier", "clean",
    "cleaners", "cleans", "cleanup", "clearing", "cleaves", "clefs", "clefts", "cleric",
    "clerical", "clew", "clewed", "clews", "clicked", "cliff", "climax", "climbers",
    "clinch", "cling", "clinic", "clinked", "clinking", "clipt", "clit", "cloaked",
    "cloche", "clock", "clod", "clogging", "clogs", "cloned", "cloning", "clops",
    "closer", "closing", "clot", "cloths", "clots", "clotting", "clouded", "clout",
    "clouts", "cloves", "cloys", "clubbed", "clubfoot", "clue", "clued", "cluing",
    "clung", "clunks", "cluster", "clusters", "clvii", "clxi", "clxix", "clxvii",
    "coals", "coarsen", "coarsens", "coated", "coax", "coaxing", "cobalt", "cobra",
    "cobweb", "cocaine", "coccyges", "cocked", "cockles", "cockneys", "cocks", "cocoon",
    "coda", "codas", "codding", "codex", "codger", "codices", "codified", "coed",
    "coeval", "coevals", "coffin", "cogitate", "cognacs", "cohere", "cohorts", "coif",
    "coiffing", "coils", "coined", "coke", "coked", "coking", "coldest", "colds",
    "collapse", "collar", "collate", "colliers", "collies", "colones", "colonies", "color",
    "colors", "cols", "coma", "comas", "comatose", "combed", "combine", "comely",
    "comer", "comfiest", "comfy", "comical", "coming", "comm", "commit", "commode",
    "commodes", "compacts", "company", "complete", "complex", "comply", "compo", "compound",
    "compute", "concedes", "concept", "conclave", "concoct", "condo", "condom", "condoms",
    "condones", "conduit", "confab", "confines", "confirm", "confuted", "congeal", "conic",
    "conics", "conjugal", "conk", "conking", "connives", "conquer", "conses", "consists",
    "consort", "consumed", "cont", "contend", "contexts", "contour", "contrite", "converse",
    "convey", "conveys", "convoyed", "cooed", "cooked", "cookery", "cooler", "coolest",
    "cools", "coon", "cooped", "coops", "coot", "cooties", "copeck", "copes",
    "coping", "coppers", "cops", "copses", "copulae", "copulate", "coral", "corals",
    "cordite", "core", "cores", "corked", "corms", "corn", "corncobs", "corneas",
    "corner", "cornrow", "coroners", "coronet", "corps", "corpse", "corrupt", "corsages",
    "cortex", "cosign", "cosigns", "cosmos", "cosmoses", "cosy", "cots", "cottage",
    "cotter", "couch", "cougars", "coughing", "coughs", "could", "country", "coupes",
    "coups", "courage", "couriers", "courtly", "courts", "cover", "coverlet", "covers",
    "covey", "coveys", "cowards", "cower", "cowhide", "cowhides", "cowing", "cowl",
    "coxcomb", "coyly", "coyote", "cozies", "coziness", "crab", "crack", "cracked",
    "crackups", "cradle", "cradled", "craggy", "cram", "cramp", "crane", "cranes",
    "craning", "crankier", "cranny", "craps", "crashes", "crate", "crated", "cravat",
    "cravenly", "cravens", "crawls", "craws", "cray", "craze", "crazes", "crazier",
    "creaking", "cream", "creamer", "creams", "creator", "creators", "credit", "creek",
    "creeks", "creep", "creepier", "creepy", "cress", "cretin", "cretins", "crevices",
    "cribbed", "cribs", "crier", "criers", "crime", "cringe", "cringes", "crinkled",
    "crisper", "crispy", "critique", "croak", "crocked", "crocks", "crone", "crones",
    "croon", "crop", "cropped", "croppers", "cross", "crosses", "crouch", "crouched",
    "crowed", "crown", "crowned", "crucifix", "crud", "cruder", "crudity", "cruel",
    "cruise", "cruised", "crumb", "crumbled", "crumbly", "crummy", "crusaded", "crushed",
    "crust", "crusty", "cubic", "cubicle", "cubing", "cubits", "cubs", "cucumber",
    "cuddles", "cuddly", "cues", "cuing", "cull", "culled", "culprit", "cults",
    "cultural", "cumulus", "cunt", "cupid", "cupids", "cupsful", "curacy", "curative",
    "curd", "curdled", "cured", "curfew", "curie", "curios", "curlew", "curlier",
    "curls", "curries", "currying", "curs", "curse", "curtain", "curter", "curved",
    "curvy", "cushier", "cushions", "cusp", "cussed", "customs", "cuter", "cutest",
    "cutlets", "cutoff", "cuts", "cutups", "cyclamen", "cycle", "cycling", "cygnet",
    "cynical", "cystic", "czarinas", "dabbles", "dacha", "dachas", "dado", "daffy",
    "daft", "dafter", "daggers", "daintily", "dainty", "dairy", "dallies", "dally",
    "damask", "dame", "damnably", "damning", "dampen", "damps", "dams", "damsel",
    "damsons", "dancer", "dandled", "danger", "dankly", "dapperer", "dappled", "dare",
    "dared", "daring", "darned", "darning", "darns", "dart", "dashes", "database",
    "date", "dates", "daubed", "daubing", "daunt", "dawdle", "dawdles", "dawn",
    "daydream", "dazed", "dazing", "dded", "dding", "deacons", "deaden", "deadpans",
    "deafer", "deafest", "deal", "deans", "dearly", "deaves", "debacle", "debar",
    "debarred", "debate", "debater", "debs", "debtor", "debug", "debugger", "debunks",
    "debuts", "decaf", "decant", "decayed", "deceases", "decent", "decided", "decimate",
    "deck", "deckle", "decks", "declaim", "declined", "decorum", "decree", "decries",
    "decry", "dedicate", "deeded", "deeming", "deems", "deep", "deepen", "defame",
    "defamed", "defaults", "defend", "defense", "defer", "deferred", "defies", "defined",
    "deflects", "defraud", "defray", "defuse", "defused", "defusing", "defy", "deicer",
    "deicing", "deign", "delay", "delayed", "delays", "deletion", "deliria", "dell",
    "dells", "deltas", "deluding", "deluxe", "delving", "demean", "demented", "demesne",
    "demolish", "demon", "demons", "demoted", "demurs", "deniers", "denies", "denim",
    "denizens", "denser", "density", "dent", "dentin", "denuded", "depict", "deplane",
    "deplaned", "depose", "deposed", "deposits", "depot", "depute", "deputed", "deranged",
    "derby", "derided", "derive", "derricks", "descant", "desert", "deserved", "designs",
    "desist", "desk", "despairs", "despise", "destine", "destroys", "detain", "detentes",
    "detest", "detests", "detox", "detracts", "devalue", "device", "deviling", "devilry",
    "devote", "devoted", "devotion", "dewier", "dewlaps", "dhoti", "dhotis", "diabetic",
    "dial", "dialogs", "dialysis", "diaper", "dibbled", "diced", "dicey", "dicier",
    "dickered", "dickey", "dickies", "dicta", "died", "diehard", "diesel", "dieseled",
    "diff", "diffed", "differs", "digger", "digit", "digital", "dike", "dikes",
    "dilated", "dilation", "dilute", "dimer", "dimmers", "dimple", "dimples", "dims",
    "dined", "dinged", "dinghies", "dingo", "dingy", "dink", "dinkier", "dinned",
    "diorama", "dioxin", "diplomat", "dipper", "dips", "directs", "direr", "dirk",
    "dirty", "dirtying", "disarm", "disarms", "disavows", "discoed", "discolor", "discus",
    "diseases", "disgust", "dish", "dishrags", "disks", "dismal", "dismayed", "dismiss",
    "displace", "disport", "disputes", "dissed", "dissent", "distaffs", "distill", "distrait",
    "disuse", "ditched", "dithered", "ditto", "dittoes", "diva", "divans", "divas",
    "dives", "divide", "divided", "dividing", "divines", "divorced", "divots", "dizzied",
    "dizzy", "doable", "dock", "docket", "docketed", "dockets", "docks", "dodged",
    "dodging", "dodoes", "dodos", "doer", "doggedly", "dogging", "doggy", "dogies",
    "dogma", "dogs", "dogwoods", "doled", "doleful", "doling", "doll", "dollop",
    "dolly", "dolmens", "domes", "domineer", "domino", "donates", "done", "donkey",
    "donut", "donuts", "doodled", "door", "doorknob", "doormen", "doped", "dopier",
    "dopy", "dorks", "dormer", "dormers", "dory", "dosed", "dosing", "doted",
    "doth", "dotingly", "dotted", "doubled", "doubt", "doubts", "douched", "doughier",
    "dourer", "dove", "doves", "dowdier", "dowels", "downfall", "downier", "downs",
    "downturn", "dowry", "dowsed", "doze", "dozed", "dozing", "drabs", "drafted",
    "draftees", "drafty", "dragoon", "drags", "drakes", "dram", "drama", "dramatic",
    "drape", "drawer", "drawers", "draws", "dread", "dreamer", "dreaming", "dreams",
    "dredge", "dress", "dresses", "dressier", "drew", "dries", "driest", "drilled",
    "drily", "drinkers", "drinks", "drips", "driver", "drizzle", "droll", "drollest",
    "droned", "droop", "drooped", "droops", "drop", "drouth", "drouthes", "drouths",
    "drove", "drowse", "drubbed", "drubs", "drugging", "druids", "drum", "drums",
    "drunken", "dryer", "dryers", "duality", "ducat", "ducats", "duck", "ducking",
    "ducts", "dude", "dueled", "duelist", "duelists", "duels", "dues", "duke",
    "dulcet", "dullest", "dulls", "duly", "dumbly", "dumfound", "dummy", "dumpier",
    "dunce", "dune", "dunged", "dunks", "dunner", "dunning", "duns", "dupes",
    "duration", "during", "dusk", "dustbin", "dustpan", "dusts", "duties", "duty",
    "dwarf", "dwarfism", "dwelled", "dwells", "dwelt", "dyes", "dyked", "dynamo",
    "dynastic", "eager", "eagerer", "earbud", "eardrum", "earl", "early", "earmarks",
    "earmuff", "earner", "ears", "earshot", "earwig", "eased", "eases", "easily",
    "easiness", "eastern", "easy", "eatery", "eaves", "ebbs", "echoes", "echos",
    "ecliptic", "ecology", "ecru", "eddies", "edger", "edgiest", "edgy", "edible",
    "edict", "editable", "editing", "eerie", "eerier", "eery", "effaced", "effect",
    "efficacy", "effort", "egis", "egoist", "egotism", "egotists", "eider", "eiders",
    "eighty", "ekes", "eking", "elastic", "elated", "elbow", "elders", "electing",
    "elector", "elegy", "elephant", "elevate", "eleven", "elides", "elite", "elitist",
    "ellipses", "elms", "eloped", "eludes", "elusive", "elves", "embalmed", "embark",
    "embassy", "embed", "emblem", "embolden", "embryo", "emend", "emended", "emeralds",
    "emerge", "emirate", "emission", "emit", "emits", "emote", "emoted", "empanel",
    "emphatic", "employ", "emporia", "empties", "emulated", "emus", "enamels", "enamor",
    "encamped", "enchant", "encode", "encored", "encoring", "ended", "ending", "endings",
    "endorser", "endues", "endured", "enema", "enemies", "energy", "enforced", "engine",
    "engorge", "engraver", "enigmas", "enjoys", "enlarger", "enmity", "ennoble", "ennobles",
    "ennui", "enrich", "enrolls", "ensconce", "ensue", "ensued", "ensures", "ensuring",
    "entail", "enthuse", "enthuses", "entire", "entrance", "entraps", "entwine", "enure",
    "enured", "envelops", "envies", "eons", "epaulet", "epigrams", "epilog", "epistle",
    "epoch", "epoxies", "epoxying", "equaled", "equine", "equinox", "equip", "equipage",
    "erased", "erect", "erectly", "erects", "ergo", "erotic", "erotics", "errata",
    "error", "errs", "ersatz", "erudite", "eruption", "escort", "escorted", "escorts",
    "espies", "esquires", "essayed", "esteem", "ester", "estrogen", "etchers", "etches",
    "ethos", "eulogy", "eunuchs", "euphoric", "euro", "evade", "evaded", "evenest",
    "evenly", "eventide", "every", "eves", "eviler", "eviller", "evillest", "evoke",
    "evoked", "ewer", "exact", "exacted", "exalts", "example", "exampled", "excel",
    "except", "excising", "excite", "excited", "excl", "excrete", "execrate", "exerting",
    "exhale", "exhaled", "exhumed", "exile", "exiled", "existent", "exit", "exited",
    "exotics", "expanses", "expect", "expel", "expense", "expert", "expiring", "explode",
    "exponent", "export", "exposes", "extent", "exterior", "extinct", "extol", "extort",
    "extrude", "extrudes", "exudes", "exult", "eyed", "eyelash", "eyelet", "eyesores",
    "fables", "facades", "faced", "facets", "facially", "fact", "factor", "factory",
    "facts", "fades", "faeces", "faggots", "fagots", "fags", "faint", "faintly",
    "fair", "fairer", "fairings", "faith", "fakers", "fakes", "falcon", "fall",
    "fallacy", "fallowed", "falls", "falsest", "falter", "famish", "famously", "fanatic",
    "fancy", "fandom", "fanfare", "fans", "faraway", "farce", "fares", "farewell",
    "faring", "farrow", "fart", "fascism", "fashions", "fasten", "fasting", "fasts",
    "fate", "fates", "fatherly", "fatigue", "fating", "fatties", "faucet", "fauna",
    "faunae", "favor", "favoring", "fawn", "faxes", "faxing", "feared", "fearful",
    "fears", "feat", "featured", "febrile", "fecal", "fedora", "feed", "feeding",
    "feeds", "feeler", "feelings", "feet", "feint", "feisty", "felines", "feller",
    "felted", "felts", "feminism", "femoral", "femurs", "fences", "fend", "fends",
    "ferment", "fern", "ferns", "ferret", "fertile", "fervidly", "fervor", "fetal",
    "fetched", "fetich", "fetid", "fettle", "feud", "feuds", "fevered", "feverish",
    "fevers", "fezes", "fiasco", "fibula", "fibulae", "fiche", "fiddle", "fiddler",
    "fief", "fielders", "fields", "fiend", "fiercer", "fifes", "fifths", "fight",
    "fighter", "fighting", "filches", "file", "files", "filets", "filled", "filling",
    "fillings", "filly", "film", "filmed", "filmy", "finale", "finales", "finalist",
    "finch", "finding", "finely", "finer", "fingered", "fining", "finis", "fink",
    "finked", "fiord", "firearm", "fireplug", "firm", "firmed", "firmest", "firms",
    "firths", "fish", "fishbowl", "fisher", "fishing", "fishy", "fitly", "fitness",
    "fitted", "fittings", "five", "fixates", "fixed", "fixing", "fizzes", "fizzing",
    "fizzy", "flabby", "flag", "flagging", "flags", "flailed", "flair", "flairs",
    "flame", "flamed", "flamers", "flan", "flange", "flanking", "flapper", "flare",
    "flashier", "flashy", "flatbed", "flatiron", "flats", "flaunt", "flaunted", "flaunts",
    "flaw", "flaxen", "flays", "flea", "fledged", "flee", "fleecy", "flees",
    "fleshed", "fleshing", "flexed", "flick", "flicker", "flier", "fliers", "flinch",
    "flinched", "flint", "flinty", "flip", "flirting", "flits", "flitted", "floats",
    "floes", "flog", "flood", "flooded", "floozies", "floozy", "flora", "floral",
    "florin", "florist", "flounces", "floured", "flout", "flowed", "flub", "flubs",
    "fluency", "fluff", "fluffing", "fluffs", "flukes", "fluky", "flunk", "flunked",
    "flunky", "fluorite", "fluster", "flutes", "flux", "flyer", "flyers", "flyleaf",
    "flyovers", "foams", "fobbed", "fobs", "focus", "focused", "foetus", "foghorn",
    "foghorns", "fogies", "fogs", "foil", "foils", "folded", "folds", "foliage",
    "folksy", "folly", "fomented", "fond", "fonder", "fondest", "fondus", "foods",
    "fool", "foolish", "footed", "footings", "footsie", "fops", "foragers", "foray",
    "forbad", "forbade", "forcing", "forded", "fords", "fore", "forebear", "forelegs",
    "foremen", "foreseen", "forewent", "forfeit", "forged", "forget", "forgive", "forgo",
    "formals", "format", "formerly", "forsworn", "fort", "forte", "fortes", "forties",
    "forty", "fossils", "foster", "foully", "fouls", "foundry", "fountain", "four",
    "fours", "fourth", "foxes", "foxing", "foxtrot", "fracking", "frag", "frags",
    "frame", "framed", "framers", "francs", "franking", "frantic", "frats", "frayed",
    "freak", "freckle", "free", "freebees", "freeman", "freer", "freest", "freeways",
    "frenzy", "frescoes", "frescos", "fretful", "frets", "fridge", "friended", "frier",
    "frigate", "fright", "frilly", "frisk", "friskier", "frisky", "fritter", "frock",
    "frogging", "frolics", "from", "fronds", "front", "frosty", "frothing", "frown",
    "frowned", "frowns", "frugal", "fruiting", "frump", "frumps", "frying", "fucker",
    "fucks", "fuddles", "fudges", "fuel", "fugue", "fulcra", "fulfill", "fullback",
    "fumble", "fumbled", "fumed", "fums", "fungal", "fungi", "fungous", "funkiest",
    "funky", "funnel", "funnies", "furl", "furlong", "furor", "furors", "furrowed",
    "further", "fury", "fused", "fusing", "fusses", "fussily", "fussy", "futz",
    "futzed", "fuzed", "fuzzball", "fuzzed", "fuzzier", "gabble", "gabbled", "gabby",
    "gabs", "gadfly", "gaff", "gaffes", "gaffs", "gages", "gaggles", "gaging",
    "gain", "gaits", "galactic", "galaxy", "gale", "gallant", "galley", "gallons",
    "galls", "galore", "gals", "gambler", "gambol", "gamboled", "games", "gamete",
    "gamin", "gaming", "gander", "ganders", "gang", "gangs", "gangster", "gannet",
    "gantlet", "garage", "garb", "garbles", "garbs", "gardenia", "gargle", "garment",
    "garner", "garotte", "garotted", "garret", "gashing", "gasket", "gasses", "gassiest",
    "gassy", "gastric", "gate", "gates", "gauche", "gaudier", "gaunt", "gauntlet",
    "gavel", "gavels", "gawk", "gawkier", "gawky", "gayety", "gazed", "gazelle",
    "gazing", "gear", "gears", "geeing", "geekier", "geekiest", "geeky", "gees",
    "geld", "gelded", "gelds", "gelling", "gems", "genera", "genetic", "genetics",
    "genie", "genome", "gent", "gentled", "gentling", "gently", "gents", "geology",
    "gerbil", "germinal", "germs", "getaway", "gets", "gherkin", "ghetto", "ghost",
    "ghoulish", "giants", "gibbon", "gibbons", "gibed", "gifts", "gigabit", "gigged",
    "gigglers", "gigolo", "gigs", "gilding", "gilt", "gilts", "gimpy", "ginger",
    "gingkoes", "gingkos", "gird", "girded", "girders", "girls", "girted", "girting",
    "gismo", "gist", "givens", "gives", "gladdest", "gladly", "glads", "glamors",
    "glands", "glass", "glassed", "glassing", "glassy", "glean", "gleans", "glee",
    "gleeful", "glide", "glider", "glimpse", "glimpses", "glitch", "gloat", "gloating",
    "glob", "globed", "globule", "gloom", "glosses", "glossier", "glossy", "glove",
    "glow", "glowed", "glued", "glueing", "glumly", "glut", "gluts", "gluttony",
    "gnarled", "gnarly", "gnats", "gnome", "gnomes", "gnus", "goal", "goalies",
    "goals", "goatskin", "gobbed", "gobbles", "goblin", "godless", "gods", "gofer",
    "gofers", "goggled", "goitre", "goldfish", "golf", "golfer", "golfs", "gollies",
    "gonad", "gong", "gonged", "gonks", "goodbys", "goodly", "goods", "goof",
    "goofs", "gooier", "gooiest", "gooks", "goop", "gopher", "gored", "gorgeous",
    "gorilla", "goring", "gorp", "gorps", "gotcha", "gouge", "gouger", "gougers",
    "gout", "gouty", "governed", "governs", "gowned", "grab", "grace", "graded",
    "graders", "graffito", "graft", "grafts", "grammar", "grams", "grandeur", "grandma",
    "grange", "granola", "grant", "grapes", "graphing", "grapple", "grasp", "grated",
    "gratify", "gratings", "gratis", "grave", "graven", "graving", "gray", "grayer",
    "grays", "grazing", "grease", "grebe", "grebes", "greedily", "greener", "greet",
    "grew", "greyed", "greyest", "gribbles", "grids", "grieve", "grieves", "grill",
    "grim", "grimaces", "grimed", "grimier", "grind", "gringo", "griping", "grippe",
    "grips", "grislier", "grit", "grizzly", "groan", "groans", "grok", "groks",
    "groomed", "grooming", "grooms", "groped", "gross", "grosser", "grouch", "grounded",
    "grouped", "grouted", "grouts", "grove", "grower", "growling", "grows", "growths",
    "grubby", "grue", "gruel", "gruffly", "grumbler", "grungy", "grunt", "guava",
    "guavas", "guerilla", "guesser", "guest", "guided", "guilder", "guile", "guiltily",
    "guinea", "gulag", "gulags", "gull", "gulley", "gulling", "gulls", "gulps",
    "gums", "gunboat", "gunman", "gunner", "gunny", "gunsmith", "gunwale", "guru",
    "gushed", "gushers", "gushy", "gusted", "gusty", "gutless", "guts", "guyed",
    "guying", "guzzler", "guzzlers", "gybe", "gypped", "gyrates", "gyros", "hacked",
    "hackles", "hackneys", "haft", "hafts", "haggle", "haggled", "hair", "hairdos",
    "haired", "hairless", "hairs", "hakes", "hales", "half", "halfway", "hallowed",
    "halo", "haloed", "haloing", "halos", "halter", "halve", "hamlet", "hammers",
    "hand", "handbag", "handbags", "handed", "handheld", "handing", "handrail", "handset",
    "hanged", "hangmen", "hangouts", "hangs", "hankie", "hapless", "happy", "harbor",
    "hard", "hardback", "hardest", "hardly", "hardtops", "harem", "hark", "harked",
    "harkens", "harks", "harness", "harped", "harpy", "harridan", "harried", "hart",
    "harts", "hashes", "hashish", "hassocks", "hasten", "hastens", "hasty", "hatchet",
    "hate", "hated", "hatred", "hats", "haughty", "hauled", "hauls", "haunts",
    "haves", "hawk", "hawked", "hawking", "hawks", "hawthorn", "haying", "haymows",
    "haze", "hazed", "hazels", "hazmat", "head", "headband", "headers", "headrest",
    "heads", "healed", "healers", "heaped", "heaps", "hear", "hearken", "hears",
    "hearties", "hearts", "heater", "heathen", "heats", "heaven", "heavies", "hectare",
    "hectares", "hector", "hedge", "heed", "heeded", "heehaws", "hefted", "hefts",
    "hegemony", "heinous", "heir", "heirs", "helium", "helixes", "hell", "hello",
    "helots", "helping", "helpings", "helps", "hemmed", "hemp", "hennaing", "henpeck",
    "herald", "herb", "herbs", "herder", "herding", "here", "hereof", "heresies",
    "hernia", "heroics", "heroin", "heron", "hertzes", "hesitate", "hewed", "hewers",
    "hewn", "hexes", "hiatus", "hickeys", "hidden", "hide", "hided", "hies",
    "highball", "higher", "highway", "hijacked", "hiked", "hiking", "hill", "hills",
    "himself", "hind", "hinds", "hinges", "hings", "hint", "hipper", "hipping",
    "hippy", "hireling", "hiss", "hissed", "hitch", "hitches", "hitter", "hoagy",
    "hoards", "hoarier", "hoarsest", "hoary", "hoax", "hoaxes", "hobbits", "hobnob",
    "hock", "hockey", "hocks", "hoed", "hoedown", "hoists", "hokey", "hokiest",
    "hold", "holdouts", "holdup", "holed", "holiest", "holler", "holly", "hologram",
    "homages", "home", "homepage", "homers", "homes", "homies", "homilies", "hominy",
    "honchos", "hone", "honed", "honey", "honied", "honoring", "honors", "hooch",
    "hoodies", "hoodoo", "hoof", "hoofs", "hooker", "hookers", "hooped", "hoops",
    "hooray", "hoorays", "hoot", "hooves", "hoped", "hopeless", "hopper", "hops",
    "hording", "horned", "horns", "horribly", "horrify", "horsed", "horsy", "hosing",
    "hospice", "hospital", "host", "hosting", "hosts", "hotbed", "hotheads", "hotlink",
    "hotly", "houmus", "hounded", "house", "housed", "hovers", "howdy", "howitzer",
    "howl", "howling", "hubbub", "hubs", "huddle", "huddles", "huff", "huffs",
    "huger", "hugest", "hula", "hulling", "hulls", "humanity", "humans", "humbles",
    "humbug", "hummock", "hummocks", "hummus", "humor", "hump", "humus", "hundred",
    "hung", "hungrier", "hungry", "hunter", "hunts", "hurdler", "hurl", "hurler",
    "hurrayed", "hurrays", "hurtles", "hurts", "hushed", "husk", "husker", "huskies",
    "hussy", "hustler", "hutzpa", "hyacinth", "hybrids", "hydra", "hydras", "hymen",
    "hymnal", "hype", "hypes", "hyphens", "hyping", "hypnotic", "ibex", "ibises",
    "iced", "icicle", "icier", "iciness", "icing", "ickier", "icky", "ideas",
    "identify", "ides", "idiots", "idled", "idling", "idol", "idolizes", "idols",
    "idyls", "iffiest", "iffy", "ignite", "ignobly", "illness", "ills", "illus",
    "illusive", "images", "imbed", "imbibes", "imbued", "imitator", "immortal", "immure",
    "immured", "impale", "impaled", "impasses", "impeded", "impel", "impels", "impiety",
    "impishly", "implode", "import", "imported", "impound", "imprison", "impurely", "impurer",
    "impute", "inanity", "inapt", "inbred", "incense", "incensed", "inch", "inches",
    "incited", "inclined", "income", "incrust", "incubate", "incur", "indeed", "indices",
    "indigo", "indirect", "inducts", "indued", "industry", "inept", "inertly", "infant",
    "infer", "inferior", "infest", "infests", "inflamed", "inflect", "inform", "informer",
    "ingots", "ingrain", "inhabits", "inhaled", "inhibit", "inimical", "initio", "injures",
    "inked", "inkier", "inkiness", "inks", "inland", "inline", "innards", "inner",
    "inning", "inns", "inquests", "inroads", "insane", "insert", "inserted", "insider",
    "insists", "insole", "inspects", "instals", "instil", "instils", "insulate", "insures",
    "intact", "intel", "intense", "intenser", "interj", "internes", "intone", "intones",
    "intrench", "intro", "inured", "invaded", "invaders", "inverse", "inverses", "invert",
    "invoice", "invoke", "involves", "iodize", "iodizes", "iota", "iotas", "iridium",
    "irking", "iron", "irons", "irrigate", "island", "islet", "isms", "isobars",
    "issued", "itched", "itchier", "itchiest", "itchy", "ivory", "jabbed", "jabbers",
    "jabs", "jackal", "jackdaws", "jacking", "jaded", "jagged", "jags", "jailer",
    "jailing", "jails", "jamb", "jammed", "japanned", "japed", "jargon", "jarring",
    "jars", "jaunts", "jawed", "jaywalk", "jaywalks", "jazz", "jazzed", "jeeps",
    "jeer", "jehad", "jejune", "jellies", "jelly", "jerk", "jerked", "jerkins",
    "jested", "jests", "jeweled", "jeweling", "jewels", "jibe", "jibed", "jiffy",
    "jigged", "jiggers", "jigsaw", "jilt", "jilting", "jimmy", "jingling", "jinnis",
    "jinx", "jinxing", "jitney", "jived", "jobber", "jobless", "jock", "jogged",
    "joggled", "joggling", "johns", "join", "joined", "joint", "joists", "joker",
    "jollied", "jolt", "jolts", "jonquil", "joshed", "jotted", "jounces", "journals",
    "joust", "jousts", "jowl", "joyous", "joyride", "jubilant", "judge", "jugged",
    "juggler", "jugs", "juicer", "juicily", "julep", "jumble", "jumbled", "jumbling",
    "jumper", "jumpy", "juncoes", "junior", "junk", "junkie", "junkier", "junks",
    "jurist", "juror", "justice", "justices", "justly", "jute", "kaftan", "kaput",
    "karaoke", "karate", "kayak", "kazoos", "kebab", "keel", "keened", "keening",
    "keens", "keep", "keeper", "keepsake", "kens", "kernel", "kernels", "keyed",
    "keyhole", "keynotes", "keys", "kibitz", "kicker", "kicking", "kickoffs", "kicks",
    "kiddie", "kiddo", "kiddoes", "kids", "killed", "kiln", "kilning", "kilns",
    "kilogram", "kilter", "kind", "kinda", "kindle", "kindles", "kinglier", "kings",
    "kinkier", "kiosk", "kiosks", "kippers", "kiss", "kissed", "kith", "kiting",
    "kitty", "kludged", "kluged", "klutz", "knacks", "knave", "knavish", "kneaders",
    "knee", "kneel", "kneels", "knelled", "knelt", "knight", "knitwear", "knob",
    "knobs", "knocked", "knocks", "knoll", "know", "knowings", "knows", "koalas",
    "kooks", "kopecks", "kosher", "krone", "kronor", "kudzu", "labelled", "labial",
    "labials", "labor", "labs", "lacing", "lacks", "laconic", "lactates", "lactic",
    "lacunas", "lacy", "laddie", "laden", "ladles", "lads", "lager", "laggard",
    "lagoon", "laid", "lake", "lakes", "lambaste", "lambing", "lame", "lamed",
    "lamely", "lames", "laming", "lampreys", "lams", "lancer", "lancers", "landed",
    "lands", "landslid", "languor", "lank", "lapel", "lapidary", "lapped", "lapping",
    "laptop", "larches", "lards", "larger", "largo", "lariats", "lark", "larked",
    "larvas", "lased", "lash", "lashed", "lassie", "lassies", "lasso", "lassoing",
    "lastly", "late", "latency", "later", "latest", "lathe", "latter", "lattice",
    "lattices", "laud", "lauds", "laughs", "launders", "lavish", "lawgiver", "lawless",
    "lawn", "laxer", "laxity", "layer", "layered", "layman", "layout", "laze",
    "lazily", "laziness", "lazying", "leach", "leaden", "leaf", "leafier", "leafy",
    "league", "leakier", "lean", "leanness", "leans", "leaped", "leapt", "learned",
    "leased", "leash", "leaven", "leavens", "lecithin", "lecture", "ledge", "ledges",
    "leek", "leers", "leeward", "left", "lefter", "leftmost", "lefts", "legally",
    "legals", "legged", "leggiest", "legging", "leggy", "legless", "legman", "lemmas",
    "lemme", "lend", "lender", "lenders", "lends", "lent", "lentil", "leopard",
    "leotards", "lessee", "lessees", "lessor", "lest", "letters", "letup", "letups",
    "levelers", "lever", "levers", "levying", "lewd", "lewder", "lexica", "liaises",
    "liaisons", "libel", "libels", "libidos", "libretti", "lice", "lichens", "licked",
    "licks", "lied", "lieges", "lies", "life", "lifeboat", "lifer", "ligament",
    "lighten", "lights", "liked", "likening", "likes", "liking", "lilt", "lilted",
    "lilting", "lilts", "lime", "limed", "limier", "limns", "limo", "limped",
    "limpest", "limpid", "linchpin", "linden", "line", "lined", "lineman", "liner",
    "liners", "lingerie", "lingos", "linings", "linker", "links", "linseed", "lintel",
    "lion", "lipid", "liquefy", "liqueurs", "liquor", "lire", "lisps", "lissome",
    "list", "listen", "liter", "literals", "liters", "lithest", "litter", "liveable",
    "liven", "livened", "livers", "livid", "living", "llano", "llanos", "load",
    "loading", "loafer", "loamiest", "loamy", "loan", "loathe", "loathed", "lobby",
    "lobs", "lobster", "local", "locale", "locating", "locker", "lockets", "loco",
    "locus", "locust", "locusts", "lodges", "lodgings", "lofts", "logbook", "loge",
    "logic", "logins", "logoffs", "logons", "logos", "logs", "lolcat", "lolls",
    "lollygag", "lone", "longed", "longing", "longtime", "looked", "looks", "loom",
    "looney", "looneys", "loony", "loop", "loose", "loosen", "loosens", "looted",
    "loped", "lopped", "lopping", "lops", "lorn", "lorry", "losing", "lost",
    "lots", "lotto", "louder", "loudest", "loudness", "louse", "louses", "louvers",
    "love", "loved", "lovelorn", "loving", "lowed", "lowing", "lowland", "loxes",
    "loyalist", "loyalty", "luaus", "lube", "lubing", "lucid", "lucking", "lucre",
    "lugs", "lumbago", "lumbar", "luminous", "lumped", "lumpy", "lunch", "lunched",
    "lung", "lunges", "lupin", "lurches", "lured", "lurid", "lurked", "luscious",
    "lush", "lushes", "lustier", "lustre", "lusty", "lute", "lxiv", "lying",
    "lynxes", "lyre", "lyrical", "macaw", "maces", "machetes", "macing", "madam",
    "madame", "madcaps", "madder", "made", "madras", "madrasa", "madrasas", "magma",
    "magnate", "magnates", "magnet", "magpies", "maidenly", "mail", "mailed", "mailing",
    "maims", "mainly", "maize", "majestic", "majored", "make", "makers", "makes",
    "malice", "maligns", "mallards", "mallow", "malt", "malting", "malts", "mamma",
    "mammal", "manacle", "mandarin", "mandate", "mane", "manful", "manfully", "manga",
    "mangle", "mangoes", "mangy", "manias", "manifest", "manikin", "manly", "manor",
    "manors", "mansard", "mansards", "mantes", "mantra", "mantras", "mapped", "mappings",
    "maps", "marabou", "maraud", "march", "marched", "mariachi", "marina", "mariner",
    "markedly", "market", "marking", "marks", "marmot", "marquess", "marquis", "marrow",
    "mars", "marshal", "martinis", "martins", "marts", "martyr", "masc", "mashed",
    "mashing", "mashup", "mason", "mass", "massage", "massed", "masseuse", "mastery",
    "matchbox", "mated", "math", "mating", "matron", "matrons", "matt", "mattress",
    "matts", "mature", "maturer", "matzot", "maunder", "mauve", "mavin", "mavins",
    "maxillas", "maxim", "maybes", "maydays", "mayhem", "mayo", "mazes", "meager",
    "meal", "mealtime", "meander", "means", "meat", "meatier", "meatiest", "meats",
    "meccas", "medal", "medial", "medical", "medicals", "medics", "meekly", "meeting",
    "meetings", "meets", "megs", "melodic", "melody", "melon", "meltdown", "member",
    "meme", "memos", "menaced", "menage", "menial", "menials", "menorahs", "mentor",
    "menu", "meowing", "meows", "mere", "merge", "merged", "meringue", "merino",
    "merited", "mermen", "merry", "meshing", "mess", "messed", "messiest", "mestizo",
    "metal", "meteor", "metes", "meting", "metrical", "metrics", "mewing", "mewl",
    "mewls", "miasma", "mica", "micra", "microns", "midair", "midget", "midmost",
    "midst", "midterms", "midwife", "miff", "might", "mighty", "migraine", "milch",
    "mildest", "mildew", "mile", "miles", "military", "milk", "milked", "milkier",
    "milky", "millage", "miller", "millrace", "mime", "mimes", "miming", "mimosas",
    "mince", "minded", "miner", "mineral", "mini", "minima", "minimize", "minimum",
    "minion", "minis", "minster", "mint", "mints", "minuends", "minuet", "minus",
    "minuted", "mirage", "mirages", "mirth", "miscalls", "miscue", "misdeal", "misdoing",
    "misfire", "misfit", "misled", "mismatch", "misplay", "misrules", "misses", "missing",
    "missteps", "mistier", "mistrust", "mists", "misused", "mite", "miters", "mites",
    "mixed", "mixing", "mixture", "moan", "moans", "mobbed", "mobs", "mobsters",
    "mocker", "mockers", "mocks", "models", "modem", "moderns", "modest", "modifies",
    "mods", "modulo", "mogul", "moiety", "moisten", "molar", "molded", "moldiest",
    "molding", "moles", "moll", "molten", "molts", "moments", "momentum", "moms",
    "money", "monger", "mongered", "mongrel", "monkey", "monogamy", "monsieur", "monsoon",
    "mooch", "mooches", "mood", "mooed", "moonshot", "moored", "moors", "moos",
    "mooting", "mope", "moped", "moping", "morale", "moray", "morbid", "mordant",
    "mordants", "morn", "moron", "morose", "morsels", "mortal", "mortgage", "mortise",
    "mosque", "mossy", "mote", "motels", "mothball", "moths", "motile", "motiles",
    "motored", "motorist", "motors", "motto", "mounds", "mourn", "mourned", "mourners",
    "moused", "mousse", "moussed", "mousy", "move", "movement", "mover", "movies",
    "mowed", "mowing", "much", "mucks", "muddied", "muddy", "mudslide", "muesli",
    "muezzin", "muffle", "mugger", "muggers", "muggy", "mugs", "mulatto", "mulching",
    "mullah", "mullion", "mulls", "mumble", "mummery", "mummy", "munching", "mung",
    "munging", "mungs", "murals", "murky", "muscatel", "muscle", "muscled", "muse",
    "mushes", "mushy", "musings", "musket", "muskiest", "musky", "muss", "musses",
    "mussier", "musty", "mutable", "mutate", "muteness", "mutes", "muting", "mutt",
    "mutual", "muumuus", "mynahs", "mynas", "myriad", "mystical", "mystics", "nabbed",
    "nabs", "nacho", "nadirs", "naiad", "naiades", "nailed", "naked", "name",
    "names", "nannies", "napalm", "nappier", "nappy", "narc", "narcosis", "narked",
    "narwhal", "nary", "nasal", "nasalize", "nation", "nations", "natty", "naughts",
    "nausea", "nautilus", "navel", "navy", "nearby", "nearing", "nearly", "neat",
    "neath", "necked", "necktie", "necrosis", "need", "needle", "needles", "needy",
    "negligee", "neighs", "neither", "nephews", "nerdiest", "nerdy", "nerves", "nervy",
    "nest", "nestled", "nether", "nettle", "nettled", "neurotic", "neutron", "newbie",
    "newel", "newsboy", "newsboys", "newsy", "newt", "newton", "nibbled", "nice",
    "nicely", "nicer", "nicked", "nickles", "nickname", "nicks", "nieces", "nigga",
    "nigger", "nigh", "nighest", "nighty", "nimblest", "nimbus", "nines", "ninny",
    "ninths", "nippers", "nite", "niter", "nitrate", "nitrogen", "nitwit", "nixes",
    "nobles", "nodal", "nodes", "nods", "nodule", "nodules", "noes", "noisy",
    "nomadic", "nomads", "nondairy", "nonskid", "nontoxic", "noodle", "nooks", "noon",
    "noonday", "north", "northern", "nose", "noses", "noshed", "nostrum", "nosy",
    "notarize", "notary", "noted", "nothing", "noting", "notworks", "nougats", "nought",
    "nous", "novae", "novices", "noway", "nozzle", "nuances", "nuclei", "nude",
    "nudes", "nudges", "nugget", "nuggets", "nukes", "null", "number", "numbing",
    "numerate", "nurse", "nursed", "nursery", "nutrias", "nuts", "nutshell", "nutted",
    "nylon", "oafish", "oared", "oars", "oarsman", "oaten", "obey", "obeying",
    "obeys", "obituary", "object", "obloquy", "oboe", "oboes", "oboist", "obscured",
    "observe", "obsolete", "obtuse", "obviated", "obvious", "occurred", "occurs", "ocher",
    "octagon", "octave", "octet", "ocular", "oddball", "odious", "odium", "odor",
    "odorless", "offal", "offends", "offing", "offings", "offloads", "often", "oftener",
    "ogre", "ogres", "oilier", "oils", "okay", "okayed", "okays", "olden",
    "oleander", "olive", "omegas", "omen", "ominous", "omits", "once", "oneself",
    "online", "onrushes", "onset", "onto", "onuses", "oops", "oozing", "opal",
    "opals", "opaqued", "opener", "opening", "operated", "opiate", "opine", "opioids",
    "oppose", "opposite", "optic", "optical", "opting", "opus", "oracle", "oracular",
    "oranges", "orate", "orates", "orbital", "orchid", "orcs", "ordered", "orders",
    "ordinary", "organ", "orgasms", "orgies", "oriented", "oriole", "orioles", "ornery",
    "ossifies", "ossify", "ostrich", "otter", "otters", "ouch", "oust", "ouster",
    "ousts", "outback", "outcomes", "outdid", "outdone", "outed", "outfoxes", "outgrow",
    "outing", "outlet", "outlets", "outlived", "outpost", "outranks", "outset", "outsets",
    "outsized", "outtake", "outwards", "outworn", "ovals", "oven", "overage", "overbear",
    "overdoes", "overeat", "overgrow", "overjoys", "overlong", "overly", "overpay", "override",
    "overs", "oversell", "overtly", "overtone", "ovulated", "ovule", "owed", "owlet",
    "owlets", "owls", "oxbow", "oxbows", "oxidize", "oxygen", "pace", "paced",
    "pacifism", "pacing", "packets", "packs", "padded", "paddles", "padre", "pads",
    "paeans", "paged", "paginate", "paging", "paid", "pails", "painful", "paint",
    "pair", "paired", "paisley", "palatial", "palazzi", "paler", "palest", "pallet",
    "palling", "palm", "palmiest", "palms", "palsies", "paltrier", "paltry", "panda",
    "pandas", "panderer", "panders", "pane", "panes", "panics", "panoply", "pansy",
    "pant", "pantie", "pantries", "papal", "papaw", "papaws", "papayas", "papery",
    "parable", "paradigm", "paramour", "parapet", "pardon", "pardoned", "pardons", "pare",
    "pared", "paring", "parkas", "parking", "parks", "parlor", "parodied", "paroled",
    "parred", "parries", "parsed", "parsnip", "part", "partaken", "parted", "parties",
    "partners", "parts", "paschal", "pasha", "passed", "passes", "passions", "passive",
    "past", "pastes", "pastime", "pastoral", "pastry", "pasts", "patches", "patented",
    "pates", "pathos", "patinas", "patois", "pats", "patsy", "patted", "pattered",
    "pattern", "pauper", "paupers", "pause", "pawed", "pawing", "pawn", "payable",
    "payday", "payed", "paying", "payrolls", "pays", "paywall", "peace", "peahens",
    "peaked", "peaks", "pear", "pearls", "pears", "pebbled", "pebbly", "peck",
    "pecks", "pectoral", "pedaled", "pedals", "peddling", "pedlar", "peed", "peeking",
    "peeks", "peeled", "peep", "peerages", "peering", "peers", "peeved", "pegged",
    "pegs", "pelican", "pelts", "pelves", "penchant", "pencils", "pend", "pended",
    "pends", "penis", "penlite", "penlites", "pennon", "pension", "peon", "peony",
    "pepped", "peppers", "percale", "percales", "perform", "perigees", "peril", "perils",
    "periods", "perjurer", "perked", "perm", "perming", "perms", "person", "persona",
    "personal", "perused", "pervades", "peseta", "peskier", "pesos", "pest", "petals",
    "peter", "petiole", "petite", "petition", "pettily", "pewees", "pews", "phage",
    "phages", "phallus", "pharmacy", "phases", "philter", "phish", "phobia", "phoebes",
    "phone", "phoned", "phonied", "phoniest", "phooey", "phrasal", "phrase", "phyla",
    "pianos", "piazzas", "piccolos", "picked", "pickier", "pickle", "picky", "picnics",
    "pictures", "piddle", "piecing", "pied", "pieing", "piers", "pigeon", "piggies",
    "pigmy", "pigpen", "pigpens", "pigs", "pigtails", "piker", "pilaff", "pilau",
    "pilaws", "pile", "piled", "pilfers", "piling", "pilling", "pillowed", "pilot",
    "pilots", "pimento", "pimply", "pinches", "pine", "pined", "pining", "pinioned",
    "pinkest", "pinkie", "pinks", "pinning", "pins", "pinto", "pinups", "pious",
    "pipe", "pipes", "pipits", "pippins", "piques", "piranhas", "pissed", "pissing",
    "pistol", "pita", "pitch", "pitches", "pitiably", "pitiful", "piton", "pitons",
    "pity", "pixels", "pixie", "pizzas", "placard", "placenta", "placid", "placket",
    "plaid", "plaids", "plait", "plaited", "plaits", "plan", "planet", "planner",
    "planners", "plans", "plaque", "plateau", "plateful", "platen", "platypi", "playable",
    "playing", "playoffs", "plays", "plazas", "pleas", "pleased", "pleats", "plebeian",
    "pled", "plenary", "plexus", "plied", "plinth", "plodded", "plonk", "plonking",
    "plot", "ploughs", "plover", "plows", "plucked", "plucky", "plug", "plugs",
    "plumbing", "plume", "plumes", "pluming", "plunged", "plunk", "plunks", "plus",
    "plushier", "plushy", "plusses", "pockets", "pocks", "podded", "poem", "poesy",
    "poetry", "pogroms", "point", "pointers", "pointy", "poker", "pokers", "pokiest",
    "poking", "poky", "polar", "poles", "polestar", "poling", "politic", "politics",
    "polity", "poll", "pollen", "polls", "polonium", "polymer", "pommel", "pomp",
    "pompous", "ponder", "pondered", "pones", "pontoon", "pony", "poohed", "pool",
    "pools", "pooping", "poorer", "pope", "popes", "poplin", "popover", "populace",
    "porch", "poring", "pork", "porno", "port", "portage", "portaged", "ported",
    "portico", "portrays", "poser", "poseur", "posing", "posit", "posited", "poss",
    "possum", "postdate", "postdoc", "postwar", "potash", "potatoes", "potful", "pothook",
    "pots", "potted", "potters", "potty", "pouched", "pouching", "poured", "pouring",
    "pours", "powered", "powers", "poxes", "practise", "pram", "prance", "pranced",
    "prate", "prawned", "prawning", "prawns", "preach", "precious", "precise", "preen",
    "preening", "prefabs", "prefer", "preheats", "prelude", "prenatal", "prenups", "preppy",
    "prequel", "presence", "pressed", "prestige", "pretext", "prettied", "pretty", "previous",
    "prevues", "preyed", "preys", "prick", "prickly", "pricks", "pried", "priest",
    "prig", "primate", "prime", "primer", "primmest", "prince", "printed", "prior",
    "prioress", "priory", "prissy", "private", "privy", "probable", "probed", "probing",
    "proctor", "procured", "prods", "profane", "profaned", "profuse", "progress", "prolix",
    "promise", "promoter", "prompt", "proms", "proof", "proofed", "propel", "prophecy",
    "prorate", "prorated", "prose", "protean", "protocol", "proudly", "prove", "proved",
    "provider", "provoke", "prow", "prowls", "proxy", "prudence", "prudent", "prying",
    "psalm", "pshaws", "puberty", "pubic", "puddle", "puddles", "pudgiest", "puff",
    "puffin", "puffing", "puffs", "puke", "pukes", "puller", "pullout", "pulped",
    "pulpiest", "pulps", "pulsate", "pulses", "puma", "pumas", "pumped", "pumpkin",
    "pundit", "pungency", "puniest", "punks", "punned", "puns", "puny", "pupal",
    "pupil", "pupils", "puppets", "pure", "pureed", "pureeing", "purer", "purged",
    "purism", "puritan", "purled", "purports", "purpose", "purrs", "purser", "pursuer",
    "purvey", "purveyor", "push", "pushes", "pushier", "pussy", "pustule", "putsch",
    "putt", "puttered", "putty", "puzzle", "puzzled", "pyres", "pyrite", "pythons",
    "quad", "quads", "quaffing", "quahog", "quake", "quaked", "quaking", "quanta",
    "quark", "quarrels", "quarter", "quarts", "quasi", "quaver", "quavers", "queasily",
    "queer", "queerer", "queers", "query", "question", "queued", "queuing", "quick",
    "quickie", "quid", "quieting", "quiets", "quill", "quilted", "quince", "quips",
    "quirk", "quirked", "quirky", "quitters", "quiz", "quizzes", "quoit", "quorum",
    "quotes", "quoth", "rabbles", "rabies", "raccoons", "raced", "races", "racial",
    "racing", "racists", "rack", "racket", "radial", "radiant", "radiates", "radii",
    "radium", "raffled", "rafted", "rafts", "raga", "rages", "raging", "raglans",
    "ragtag", "raid", "raiders", "railings", "rails", "rain", "rained", "rainier",
    "raise", "raisin", "raked", "rakish", "rakishly", "rallies", "rally", "ramp",
    "rampant", "ramrod", "ranchers", "ranches", "random", "randy", "ranges", "rank",
    "rankest", "ranks", "ransom", "ransomed", "ransoms", "rape", "rapes", "rapids",
    "raping", "rappers", "rare", "rared", "rarefy", "raring", "rarities", "rasher",
    "rashers", "rasps", "raster", "rate", "rates", "rating", "rationed", "rations",
    "rattan", "rattler", "ravages", "raved", "ravels", "raven", "ravenous", "raving",
    "ravioli", "rayon", "rays", "razing", "razor", "razz", "reacted", "reactors",
    "reacts", "readies", "reads", "reagents", "reales", "realest", "realize", "realm",
    "realty", "ream", "reaper", "reapply", "reaps", "reason", "reasoned", "rebates",
    "rebel", "rebind", "rebounds", "rebuilt", "rebut", "rebuts", "recants", "recaps",
    "receding", "recent", "recesses", "recheck", "reckon", "reckons", "recliner", "record",
    "recount", "recouped", "rector", "rectors", "recur", "recycled", "redden", "reddens",
    "redheads", "redneck", "redoes", "redrawn", "redrew", "reds", "reduces", "reducing",
    "reedy", "reek", "reeked", "reelect", "reels", "reeves", "reeving", "refer",
    "referees", "refile", "refined", "refinish", "reflex", "reforms", "refrains", "refuge",
    "refuges", "refute", "refuted", "regally", "regarded", "regent", "regexps", "regime",
    "regroup", "regulars", "rehab", "rehabs", "rehi", "reigned", "reigns", "reimpose",
    "reis", "rejoiced", "rejoin", "relabel", "relative", "relax", "relaxes", "relays",
    "relevant", "relief", "reliefs", "relive", "reliving", "relying", "remain", "rematch",
    "remedies", "remedy", "remit", "remits", "remoter", "remounts", "removes", "rename",
    "rends", "reneged", "renewing", "rennet", "rent", "rented", "renting", "reorg",
    "reorging", "reorgs", "repaint", "repays", "repels", "repented", "replace", "replies",
    "reply", "report", "reported", "reprise", "reproofs", "reputed", "requiems", "rereads",
    "reruns", "rescuer", "rescuers", "resell", "reset", "resets", "resides", "residing",
    "resist", "resolved", "resorts", "respells", "respite", "rest", "rested", "resting",
    "restless", "rests", "resulted", "resumed", "retail", "retakes", "retching", "retell",
    "retinae", "retiree", "retold", "retort", "retraces", "retract", "retried", "retrofit",
    "reunify", "reusable", "reuse", "reused", "revamps", "reveal", "reveller", "revenue",
    "reversed", "revert", "reverts", "revise", "revises", "revisits", "revoked", "revolt",
    "reward", "rewarded", "rewinds", "rework", "rewound", "rhea", "rheas", "rhino",
    "rhombi", "rhomboid", "rhubarb", "ribald", "rices", "rich", "riches", "ricked",
    "rickety", "riddle", "riddled", "rides", "ridicule", "riding", "rids", "riffle",
    "riffs", "rifling", "rift", "rifted", "rifts", "rigidity", "rigidly", "rigor",
    "rile", "riling", "rills", "rims", "rinds", "ringed", "rink", "rinks",
    "rinses", "rioters", "ripe", "ripen", "ripens", "riposte", "riposted", "ripped",
    "ripsaw", "riser", "risible", "risk", "risky", "ritual", "ritzy", "rivaled",
    "river", "riveters", "rivets", "roaches", "roads", "roadster", "roam", "roans",
    "roar", "roared", "roaring", "robed", "robing", "robot", "robotic", "robust",
    "rock", "rocket", "rocketed", "rodents", "rodeo", "roes", "rogers", "rogue",
    "roister", "role", "rolled", "rolls", "romance", "romanced", "romper", "rood",
    "roods", "rookery", "rookie", "room", "roomier", "rooms", "roost", "roosts",
    "rootless", "ropes", "roping", "rose", "rosebud", "rosins", "rostrum", "rostrums",
    "rotary", "rote", "rotor", "rotted", "rouges", "rough", "roughen", "roughing",
    "rounder", "roused", "route", "router", "rove", "rover", "rowboat", "rowdiest",
    "rowed", "rowels", "rower", "royals", "royalty", "rubble", "rubella", "ruble",
    "rubric", "rubs", "ruckuses", "rude", "rudely", "ruff", "ruffed", "ruffian",
    "ruffs", "ruggedly", "ruined", "ruinous", "ruins", "rule", "ruler", "rumbas",
    "rummage", "rummy", "rumors", "rumpuses", "rums", "rundown", "runes", "runner",
    "runny", "runoffs", "runs", "rupee", "rupees", "rush", "rusks", "russet",
    "rust", "rustier", "rustling", "rutted", "rutting", "saber", "sabre", "sabres",
    "sacked", "sacs", "saddest", "saddle", "saddling", "sadly", "safari", "safaris",
    "safety", "sagas", "sage", "sahib", "said", "sailed", "sailfish", "saint",
    "saintly", "sake", "salaam", "salary", "sales", "salients", "salines", "salmon",
    "salsa", "salsas", "salt", "saltier", "salute", "saluting", "salvage", "salve",
    "salvos", "samba", "sampans", "sample", "samurais", "sanctum", "sanded", "sandhog",
    "sandiest", "sandmen", "sandy", "sane", "sanity", "sank", "sapphire", "sarcasm",
    "saree", "sarees", "sari", "sashes", "sassier", "satanism", "satay", "sate",
    "sates", "sating", "satires", "satrap", "sauce", "saucer", "saucily", "saunaing",
    "savage", "savager", "saved", "saves", "saving", "saviors", "saviours", "savory",
    "sawdust", "sawed", "sawn", "scab", "scabbier", "scabby", "scabies", "scads",
    "scale", "scaled", "scaling", "scalpels", "scaly", "scam", "scammed", "scampi",
    "scanning", "scans", "scanted", "scar", "scarab", "scarcely", "scares", "scarf",
    "scarfed", "scarves", "scats", "scavenge", "scenic", "scent", "scepter", "schism",
    "schisms", "schlepps", "schmuck", "school", "schooled", "schwas", "science", "scoff",
    "scoffing", "sconce", "sconces", "scoop", "scoots", "scorches", "score", "scored",
    "scoring", "scorns", "scour", "scouted", "scouting", "scouts", "scows", "scraps",
    "scratch", "scratchy", "screen", "screens", "screw", "scribe", "scripted", "scrod",
    "scrods", "scrooge", "scrota", "scrunch", "scrupled", "scuba", "scubas", "scud",
    "scull", "sculled", "sculling", "scummy", "scurries", "scurvy", "scuttle", "seagoing",
    "sealed", "sealing", "seals", "seam", "seamen", "seamy", "searcher", "seasick",
    "season", "seat", "seaweed", "secede", "seceding", "secrecy", "sect", "sects",
    "secure", "secured", "securely", "sedates", "sediment", "seduce", "seeds", "seeings",
    "seek", "seeker", "seems", "seep", "seeping", "seers", "sees", "seesaw",
    "seesawed", "segues", "seizing", "seldom", "selfless", "sellers", "sells", "selves",
    "semi", "seminal", "seminary", "sending", "sends", "senile", "senses", "sentinel",
    "sepal", "sepsis", "septa", "septets", "septum", "sera", "serape", "serapes",
    "seraphic", "serf", "serge", "serial", "sermons", "serous", "serrated", "server",
    "servile", "servo", "settee", "settees", "settings", "setups", "seven", "seventh",
    "severs", "sewer", "sews", "sexier", "sexiest", "sexiness", "sexism", "sextet",
    "sexting", "shack", "shacks", "shadings", "shadow", "shadows", "shady", "shag",
    "shags", "shaikh", "shakeup", "shaky", "shallow", "shalt", "sham", "shaman",
    "shambled", "shammy", "shank", "shantung", "shanty", "shapely", "shard", "shared",
    "sharks", "sharp", "sharped", "shaven", "shaving", "shaykh", "sheaf", "shearers",
    "sheaths", "sheave", "sheen", "sheer", "sheering", "sheikh", "shekels", "shelf",
    "shelve", "shelved", "sherbets", "shes", "shied", "shield", "shift", "shilled",
    "shills", "shimmers", "shine", "shines", "shingle", "shingles", "ship", "shipping",
    "ships", "shirked", "shirks", "shirr", "shits", "shitty", "shivery", "shlemiel",
    "shlock", "shock", "shodden", "shoddy", "shoe", "shone", "shoos", "shooters",
    "shoots", "shop", "shopped", "shops", "short", "shortcut", "shortly", "should",
    "shove", "shovel", "showbiz", "showboat", "shower", "showman", "showy", "shrapnel",
    "shrew", "shrews", "shrike", "shrills", "shrimped", "shrine", "shrivel", "shrove",
    "shrunk", "shticks", "shtik", "shucks", "shuffled", "shun", "shunt", "shushed",
    "shuts", "shutting", "shuttle", "sibyls", "sicker", "sicking", "sickness", "sicks",
    "sics", "sidestep", "siding", "sidings", "sidle", "sierra", "sieves", "sift",
    "sifting", "sifts", "sighed", "sight", "signer", "signets", "signpost", "silent",
    "silk", "silkier", "silkiest", "silks", "silly", "silt", "silted", "silvery",
    "simile", "simple", "simpler", "since", "sincerer", "sine", "sinewy", "singe",
    "singes", "singled", "sinker", "sinkhole", "sins", "sinuous", "sinus", "siphon",
    "sires", "sirocco", "sirs", "sirups", "sises", "sitar", "sitcom", "sits",
    "sitting", "sixes", "sixpence", "sixths", "sized", "sizes", "sizzled", "skater",
    "skein", "sketch", "sketches", "skew", "skewers", "skied", "skiers", "skiff",
    "skillet", "skimp", "skimps", "skin", "skinless", "skips", "skirted", "skirts",
    "skit", "skivvied", "skulk", "skulls", "skycaps", "skydives", "skyed", "skyward",
    "slack", "slackest", "slackly", "slacks", "slag", "slake", "slalom", "slant",
    "slanted", "slapping", "slat", "slate", "slated", "slating", "slave", "slaves",
    "slaying", "sleazy", "sled", "sledging", "sleek", "sleeked", "sleeps", "sleeve",
    "sleighs", "slept", "slewed", "slice", "slices", "slicing", "slickers", "slid",
    "slier", "sliest", "slights", "slims", "slinging", "slink", "slinks", "slipped",
    "slit", "slithers", "slits", "slog", "slogan", "slogans", "slogs", "sloppy",
    "slops", "sloshes", "sloshing", "slot", "slots", "slough", "slower", "slowing",
    "slowpoke", "slued", "slug", "sluing", "slumber", "slumlord", "slump", "slunk",
    "slurred", "slush", "slushy", "slut", "slyer", "smallest", "smalls", "smart",
    "smarted", "smeared", "smell", "smellier", "smells", "smidge", "smidges", "smile",
    "smiley", "smirking", "smith", "smiths", "smitten", "smog", "smoggy", "smokes",
    "smoky", "smolder", "smoother", "smudgy", "smugger", "smuggled", "smuts", "smutty",
    "snafu", "snag", "snailed", "snailing", "snails", "snake", "snare", "snared",
    "snaring", "snarks", "snarl", "snarling", "snatch", "sneer", "sneers", "sneezed",
    "snickers", "sniffs", "snifter", "snipe", "snipes", "snippet", "snit", "snitched",
    "snobby", "snobs", "snooping", "snoots", "snoozes", "snore", "snored", "snots",
    "snotty", "snow", "snowier", "snowiest", "snowy", "snuff", "snuffer", "snuffled",
    "snuffs", "snug", "soaking", "soaks", "soaped", "soar", "soars", "sobered",
    "soberest", "soccer", "socket", "sockets", "soda", "sodas", "sodium", "sofa",
    "softened", "softie", "soggier", "soggy", "solace", "solaces", "solar", "sold",
    "soldered", "solemn", "solid", "solidity", "solidly", "solo", "solved", "solvents",
    "solvers", "somber", "some", "sonar", "sonata", "sonatas", "songster", "sonny",
    "soon", "soothes", "sooty", "sopped", "soprano", "sorcerer", "sore", "sorely",
    "sores", "sorrow", "sorrows", "sorts", "sots", "sottish", "soughs", "soulmate",
    "souls", "souped", "soupier", "soupy", "sour", "sourer", "souring", "south",
    "souvenir", "soviet", "soya", "space", "spaced", "spacing", "spade", "spaded",
    "spangle", "spangled", "spank", "spar", "sparer", "sparest", "spark", "sparkles",
    "sparrow", "sparse", "spat", "spate", "spatter", "spatulas", "spawn", "spawns",
    "spear", "speared", "specie", "specious", "speckle", "sped", "speed", "speedier",
    "speeds", "speedup", "spend", "spends", "sperm", "spheroid", "sphinx", "spicier",
    "spicy", "spider", "spies", "spigot", "spigots", "spiky", "spillway", "spinal",
    "spindle", "spine", "spinoff", "spiraeas", "spiral", "spire", "spirit", "spit",
    "spitted", "splashed", "splat", "splats", "splice", "spliced", "splinted", "split",
    "splits", "splotch", "spokes", "sponger", "spongers", "spoof", "spoofs", "spools",
    "spoon", "spooned", "spooning", "spores", "sport", "spotted", "spotting", "spotty",
    "spout", "sprain", "sprayed", "sprays", "spree", "sprees", "spring", "springy",
    "sprinted", "sprout", "spruces", "spryer", "spud", "spume", "spunky", "spurious",
    "spurned", "spurs", "spying", "squab", "squall", "squalls", "squarely", "squashy",
    "squats", "squaw", "squeal", "squealed", "squelch", "squinted", "squire", "squirmy",
    "squish", "stab", "stabbing", "stables", "stack", "staffs", "stage", "stagger",
    "staggers", "stain", "stains", "stakes", "stale", "stalest", "stalking", "stalks",
    "stamens", "stamp", "stamps", "stanches", "stands", "stank", "stanzas", "stardom",
    "stared", "starfish", "stark", "starred", "startled", "starts", "starved", "stash",
    "stat", "stater", "station", "status", "statutes", "stave", "staving", "stayed",
    "stdio", "steaks", "steal", "steaming", "steeds", "steel", "steeped", "steeps",
    "stein", "stellar", "stem", "stemming", "stench", "stent", "steppes", "sterna",
    "sternly", "sternums", "stews", "sticks", "stickup", "stickups", "stiff", "stifle",
    "stifled", "still", "stilts", "stimuli", "stimulus", "stink", "stinks", "stipends",
    "stipple", "stir", "stoat", "stoats", "stockier", "stoics", "stoke", "stokers",
    "stokes", "stolid", "stomp", "stones", "stonier", "stood", "stools", "stooping",
    "stopped", "stops", "stores", "stories", "storm", "storming", "stormy", "stout",
    "strafe", "strafed", "strainer", "strand", "strange", "strap", "strawing", "strays",
    "streams", "street", "strep", "stretchy", "strews", "strike", "striker", "strikers",
    "strips", "strived", "strobe", "strokes", "strolled", "strong", "strop", "struck",
    "strumpet", "strut", "struts", "stub", "stubbly", "studies", "studious", "studly",
    "studs", "stumbles", "stump", "stumps", "stun", "stunk", "stunted", "stupid",
    "sturgeon", "styes", "styles", "styling", "suave", "suavely", "suaver", "subdues",
    "subheads", "sublet", "submerse", "submits", "subs", "subsidy", "subspace", "subtle",
    "subtract", "suburbs", "subway", "succors", "sucker", "suckered", "sucrose", "suds",
    "suede", "suet", "suffix", "suffixed", "suffuse", "suicides", "suing", "suited",
    "sulfate", "sulfur", "sulk", "sulkiest", "sulkily", "sulks", "sultans", "sultry",
    "sumac", "summer", "summits", "summoned", "sums", "sundae", "sundial", "sundowns",
    "sunlit", "sunnier", "suns", "suntan", "suntans", "sunup", "superber", "supine",
    "supplier", "supply", "suppose", "sure", "sureness", "surer", "surety", "surged",
    "surgeon", "surly", "surmises", "surname", "survey", "surveyor", "survive", "suturing",
    "svelter", "swag", "swags", "swains", "swallow", "swamp", "swamping", "swampy",
    "swans", "swap", "swarm", "swarms", "swarthy", "swathing", "swaths", "swats",
    "swatted", "sway", "swear", "sweats", "sweeping", "sweet", "sweeten", "sweller",
    "swells", "swift", "swiftest", "swigged", "swills", "swims", "swing", "swingers",
    "swinish", "swiped", "swish", "switch", "swivels", "swizzled", "swoops", "swop",
    "swopped", "swops", "sworn", "syllable", "symbol", "synergy", "synod", "synopses",
    "syphon", "sysops", "tabbies", "tabby", "tableaus", "tabled", "tabooed", "tabu",
    "tabued", "tabus", "tacking", "tacky", "taco", "tactic", "tactical", "tactile",
    "taffy", "tags", "tailing", "tailor", "tailwind", "taken", "talc", "talent",
    "talents", "tales", "tall", "taller", "tallies", "tally", "tallying", "tamale",
    "tamer", "taming", "tamp", "tampon", "tampons", "tangibly", "tangier", "tango",
    "tangos", "tank", "tankful", "tanks", "tanner", "tanning", "taped", "tapeworm",
    "taping", "tapir", "taproot", "taps", "tares", "target", "tariffs", "taro",
    "tarots", "tarps", "tarries", "tart", "tartan", "tartly", "tartness", "tarts",
    "tasered", "taste", "tasted", "tatted", "tatters", "tattoo", "tattoos", "taunt",
    "taunting", "taut", "tautly", "taxed", "taxicab", "taxied", "taxis", "teachers",
    "teacup", "teacups", "teak", "teals", "tear", "teared", "tearing", "teary",
    "teaser", "teaspoon", "teatime", "teats", "techno", "teem", "teemed", "teenier",
    "teens", "teeter", "telegram", "telex", "telexed", "tell", "temped", "tempered",
    "tempers", "tempo", "tempos", "tempt", "tempter", "tended", "tendered", "tending",
    "tennis", "tenon", "tenpin", "tenpins", "tens", "tenses", "tensors", "tenth",
    "tenure", "tepid", "tequila", "tequilas", "termly", "tern", "terns", "terrain",
    "terrapin", "tersest", "tested", "testicle", "testing", "tests", "tether", "text",
    "textual", "thallium", "thank", "thatch", "thaw", "theatre", "theft", "theirs",
    "theistic", "theme", "then", "thence", "therein", "thesis", "thespian", "theta",
    "thiamin", "thieved", "thigh", "thimbles", "thin", "thing", "things", "third",
    "thirdly", "thirst", "thirties", "thorax", "thorium", "those", "though", "thraldom",
    "threat", "thresher", "threw", "thrice", "thrifty", "thrive", "throats", "throe",
    "throne", "throwing", "thrown", "thru", "thrush", "thrusts", "thuds", "thump",
    "thunder", "thunks", "thus", "thwarted", "thymi", "thymus", "tibia", "tibias",
    "tickets", "tickle", "tics", "tided", "tidier", "tidiest", "tiding", "tied",
    "tiff", "tiffs", "tights", "tightwad", "tigress", "tikes", "tile", "tiled",
    "tilled", "tilts", "timber", "timbers", "time", "times", "timidity", "timing",
    "tines", "tinfoil", "tinges", "tinier", "tinkers", "tinny", "tins", "tinsel",
    "tinseled", "tinting", "tipi", "tipper", "tipples", "tipsy", "tiptop", "tiptops",
    "tire", "tiros", "titanium", "titans", "titbits", "tithe", "tithes", "titter",
    "titular", "toad", "toads", "toaster", "tocsin", "today", "toddlers", "toddles",
    "toffee", "tofu", "togae", "toggled", "togs", "toiler", "toils", "toilsome",
    "tokes", "told", "tolled", "tombing", "tomboy", "tome", "tomes", "tone",
    "toneless", "toner", "tongs", "tonics", "toniest", "tonsil", "tony", "toolbox",
    "tools", "toot", "toothy", "topaz", "topazes", "topmasts", "topmost", "topple",
    "topside", "toque", "tore", "tornados", "torpedo", "torque", "torso", "tort",
    "tortes", "torture", "tortures", "torus", "tossup", "tote", "totem", "totted",
    "totters", "touch", "touchy", "toughen", "toured", "tourist", "tourists", "tout",
    "touts", "towards", "towels", "tower", "townsman", "tows", "toxin", "toxins",
    "trace", "tracer", "tracers", "tracker", "traction", "trade", "traded", "tragedy",
    "tragic", "training", "traipse", "trait", "traits", "trample", "tranquil", "trans",
    "trap", "trapezes", "trapper", "trash", "trauma", "traveler", "travels", "tread",
    "treads", "treasure", "treated", "treble", "treed", "trefoil", "trek", "trekking",
    "treks", "trended", "trendy", "trespass", "triad", "trials", "tribute", "trice",
    "tricking", "tricks", "tries", "trifler", "trifling", "trill", "trills", "trim",
    "trimmed", "trinkets", "tripe", "triplet", "triply", "triter", "tritest", "trod",
    "troikas", "troll", "trolling", "trolls", "troop", "trooped", "troops", "tropic",
    "troth", "trotters", "trouble", "troupes", "trowel", "troweled", "troy", "troys",
    "trucker", "trucks", "trued", "trues", "truffle", "truing", "trumpets", "trunk",
    "trusses", "trustier", "trusts", "truth", "trying", "tsar", "tsarina", "tubby",
    "tuber", "tubercle", "tubing", "tubs", "tufting", "tufts", "tugged", "tugs",
    "tumbler", "tumid", "tumors", "tunas", "tundras", "tune", "tuner", "tuners",
    "tungsten", "tunny", "turban", "turbine", "tureen", "turf", "turkey", "turners",
    "turnoffs", "turnout", "turns", "turret", "tushes", "tusk", "tutored", "tutoring",
    "tutors", "tutus", "twain", "tweed", "tweeds", "tweeted", "tweezers", "twelve",
    "twerp", "twerps", "twig", "twigged", "twigs", "twinge", "twink", "twinkle",
    "twinkled", "twist", "twists", "twit", "twitted", "twitters", "tycoon", "tycoons",
    "tykes", "type", "types", "typifies", "typist", "typists", "tzar", "tzars",
    "udders", "ukelele", "ulna", "ulnae", "ultimata", "ultras", "umbel", "umiak",
    "umping", "umpires", "unaware", "unawares", "unbars", "unbind", "unbound", "unbroken",
    "uncle", "unclean", "uncoil", "uncommon", "unction", "underage", "underpin", "undid",
    "undoes", "undying", "unease", "uneasily", "unfilled", "unfits", "unfunny", "ungulate",
    "unhand", "unhappy", "unhorses", "unhurt", "unicorn", "unify", "unison", "unit",
    "unitary", "unite", "unjust", "unjustly", "unlaces", "unless", "unlisted", "unlocks",
    "unmade", "unman", "unmask", "unmasks", "unmissed", "unpacks", "unpick", "unquoted",
    "unreal", "unriper", "unroll", "unsaid", "unsalted", "unseats", "unseen", "unset",
    "unshaven", "unsold", "unstrung", "unsure", "untamed", "until", "untiring", "untold",
    "untying", "unveil", "unwanted", "unwind", "unwraps", "upbeat", "upbraids", "updater",
    "upend", "upheld", "uphills", "upkeep", "uplifted", "uppers", "upraise", "uproar",
    "upset", "upshot", "upsides", "upstaged", "upswing", "upturn", "upwardly", "urbaner",
    "urchin", "urea", "urges", "uric", "urinal", "urinary", "usage", "usefully",
    "user", "ushers", "using", "usually", "usury", "uterine", "uterus", "utilized",
    "utterly", "utters", "uvula", "vacant", "vaccine", "vagabond", "vagary", "vagrant",
    "vague", "vainer", "vale", "valence", "valid", "valley", "valorous", "valuing",
    "valve", "valved", "vandal", "vandals", "vane", "vanishes", "vaped", "vapid",
    "vaping", "variance", "varies", "variety", "varsity", "vast", "vaster", "vasts",
    "vaulter", "vaunts", "vectored", "veep", "veeps", "vegan", "vegans", "vehicle",
    "veil", "veined", "velds", "velvet", "vend", "venders", "vendor", "vends",
    "venereal", "venous", "venting", "venue", "verbatim", "verbose", "verge", "verged",
    "veriest", "verify", "vermin", "versus", "vertebra", "very", "vespers", "vessel",
    "vests", "veteran", "veterans", "veto", "vetoed", "vexes", "viable", "vibe",
    "vibes", "vibrato", "vicarage", "viced", "vicing", "victory", "videos", "vies",
    "views", "viii", "vilely", "vileness", "viler", "villas", "villein", "vineyard",
    "vinyl", "viol", "violet", "violets", "viols", "viragoes", "vireo", "vireos",
    "virgule", "virtue", "viscera", "visceral", "viscid", "vised", "visit", "visited",
    "visits", "visual", "vital", "vitiated", "vitriol", "viva", "vivify", "vixen",
    "vocalize", "vocally", "vocals", "vodka", "voice", "voices", "vole", "voles",
    "voltage", "volume", "vomited", "vomiting", "votary", "vote", "voted", "votive",
    "vouch", "vowel", "voyage", "voyager", "voyaging", "vulvas", "wackest", "wacko",
    "wackos", "wade", "waded", "waders", "wadis", "waffles", "waft", "wafted",
    "wafts", "wagering", "wages", "waggle", "waggled", "wags", "wailed", "wails",
    "wait", "waits", "waived", "waivers", "waken", "wakens", "waled", "waling",
    "walk", "walkers", "wallet", "walleye", "walleyes", "walls", "walnut", "waltzed",
    "wand", "wander", "wands", "wanks", "wannabe", "wannabes", "wanner", "want",
    "wants", "wapiti", "warbled", "warden", "warez", "warfare", "wariness", "warlord",
    "warm", "warmed", "warmth", "warns", "warp", "warping", "warred", "warship",
    "warthogs", "warty", "wary", "washes", "washout", "wasteful", "wasters", "wastes",
    "watch", "watered", "waterier", "watt", "wattle", "waved", "wavered", "waves",
    "wavy", "waxes", "waxier", "waxwings", "waylays", "weak", "weaken", "wealth",
    "wealthy", "wear", "wearable", "wearies", "wears", "weasel", "weave", "weavers",
    "weaves", "website", "wedded", "weddings", "wedgie", "weed", "weeders", "weedy",
    "weeing", "weep", "weeper", "weepers", "weepy", "weft", "weigh", "weighed",
    "weighted", "weirdo", "weirs", "welched", "welfare", "welkin", "well", "wells",
    "welter", "wench", "wenches", "wend", "wept", "westerns", "wetness", "wets",
    "whack", "whacks", "whaler", "whalers", "whamming", "whams", "wharfs", "what",
    "wheal", "wheaten", "wheezy", "whelk", "whelked", "whence", "where", "wherein",
    "wherever", "whew", "which", "whiled", "whiling", "whims", "whined", "whining",
    "whinny", "whip", "whipcord", "whips", "whirr", "whisker", "whisking", "whisks",
    "whist", "whit", "whitens", "whites", "whittled", "whizz", "whizzed", "whom",
    "whoops", "whooshes", "whopper", "whore", "whorls", "whose", "widely", "wider",
    "widget", "widgets", "widowing", "wield", "wields", "wife", "wigeons", "wigged",
    "wights", "wigwams", "wild", "wilder", "wildlife", "wilds", "wiles", "wiling",
    "will", "willies", "wilted", "wimp", "wimpled", "wimps", "winces", "winch",
    "windbag", "windfall", "wined", "wineries", "winery", "wing", "winging", "wings",
    "wining", "winning", "winnow", "wino", "wintrier", "wiped", "wiping", "wire",
    "wired", "wiriest", "wiring", "wiser", "wisest", "wish", "wispy", "wist",
    "wistful", "witchery", "withal", "witness", "wive", "wives", "wizard", "wizardry",
    "wizened", "wobbly", "woks", "wolfs", "womanly", "womb", "wombat", "wombs",
    "wonted", "woodbine", "woodcut", "woods", "woodsier", "woodsy", "wooer", "woof",
    "woofers", "wooing", "woolly", "woozier", "wooziest", "woozy", "word", "wordy",
    "worker", "workflow", "workman", "worm", "worms", "wormwood", "worried", "worse",
    "worsts", "would", "wounded", "wounding", "wounds", "wove", "woven", "wrapper",
    "wraps", "wreak", "wreaks", "wreathes", "wren", "wrens", "wrested", "wrestles",
    "wrests", "wright", "wring", "wrinkle", "wrinkles", "writer", "writs", "written",
    "wroth", "wryer", "wryest", "wryness", "xcii", "xcix", "xref", "xrefs",
    "xxiii", "xxiv", "xxvi", "xxxiii", "xxxiv", "xxxvi", "yacked", "yacks",
    "yaks", "yanked", "yanking", "yaps", "yardages", "yards", "yarn", "yawls",
    "yawned", "yaws", "yeahs", "yearned", "yeas", "yeast", "yeasts", "yellower",
    "yelped", "yens", "yeses", "yessed", "yest", "yielded", "yippee", "yips",
    "yocks", "yoghourt", "yogi", "yogis", "yogurts", "yokels", "yokes", "yolk",
    "yours", "yous", "youths", "yowls", "yucked", "yucky", "yukking", "yuks",
    "yups", "zanies", "zaniness", "zapping", "zeal", "zealot", "zebra", "zenned",
    "zens", "zeroth", "zest", "zests", "zigzags", "zincs", "zing", "zinged",
    "zinging", "zipped", "zithers", "zodiac", "zombi", "zone", "zones", "zoning"
];

function generatePassphrase() {
    const n   = Math.max(4, Math.min(20, parseInt(document.getElementById("ppWords").value) || 8));
    const sep = document.getElementById("ppSep").value;
    // Rejection-sampling: discard values >= REJECT_LIMIT to eliminate modulo bias.
    // 7776 = 6^5, so REJECT_LIMIT = floor(2^32 / 7776) * 7776 = 4 294 964 736.
    // Rejection rate ≈ 0.0001% — negligible in practice.
    const REJECT_LIMIT = 4294964736;
    const result = [];
    while (result.length < n) {
        const buf = new Uint32Array(n - result.length);
        crypto.getRandomValues(buf);
        for (const v of buf) {
            if (v < REJECT_LIMIT) result.push(PP_WORDS[v % PP_WORDS.length]);
            if (result.length === n) break;
        }
    }
    document.getElementById("ppOutput").textContent = result.join(sep);
}

function copyPassphrase() {
    const txt = document.getElementById("ppOutput").textContent;
    if (txt === "Click Generate…") return;
    navigator.clipboard.writeText(txt)
        .then(() => flash("Copied to clipboard", "success", 1500))
        .catch(() => flash("Clipboard access denied — copy manually", "warn", 3000));
}

function usePassphrase() {
    const txt = document.getElementById("ppOutput").textContent;
    if (txt === "Click Generate…") return;
    document.getElementById("password").value = txt;
    document.getElementById("passwordConfirm").value = txt;
    checkPasswordStrength();
    checkConfirmMatch();
    flash("Passphrase set as password — confirm field also filled", "success", 2500);
}

// ── Keyfile handling ─────────────────────────────────────────────────

function onKeyfileToggle() {
    const en = document.getElementById("useKeyfile").checked;
    document.getElementById("keyfilePickRow").classList.toggle("visible", en);
    if (!en) clearKeyfile();
}

function onKeyfileSelected() {
    const f = document.getElementById("keyfileInput").files[0];
    if (!f) return;
    if (f.size > 16 * 1024 * 1024) {
        flash("Keyfile too large (max 16 MB)", "warn"); return;
    }
    f.arrayBuffer()
        .then(buf => {
            keyfileData = new Uint8Array(buf);
            document.getElementById("keyfileName").textContent = `${f.name} (${formatSize(f.size)})`;
            log(`Keyfile loaded: ${escapeHtml(f.name)} (${formatSize(f.size)})`, "info");
        })
        .catch(err => {
            flash(`Keyfile read failed: ${err.message}`, "warn");
            log(`✗ Keyfile read error: ${err.message}`, "error");
            clearKeyfile();
        });
}

function clearKeyfile() {
    keyfileData = null;
    document.getElementById("keyfileInput").value = "";
    document.getElementById("keyfileName").textContent = "No keyfile selected";
}
